# Generated by Django 4.1.3 on 2022-11-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parallax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фон',
                'verbose_name_plural': 'Фоны',
            },
        ),
    ]
